name: Auto Push Changes

on:
  push:
    branches:
      - master
  workflow_dispatch:
  # Watch for any file changes
  watch:
    types: [started]

jobs:
  auto-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install chokidar for file watching
        run: npm install -g chokidar-cli
          
      - name: Watch and push changes
        run: |
          chokidar "**/*" -c "git add . && git commit -m 'Auto-commit: File changes detected' && git push" --ignore-initial 