name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deployToProduction:
        description: 'Deploy to Production'
        required: true
        default: 'true'

env:
  VERCEL_ORG_ID: ${{ secrets.SECRET_VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.SECRET_VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.SECRET_VERCEL_TOKEN }}

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.SECRET_VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.SECRET_VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.SECRET_VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod'
